package TP_Final.devhire.Security.Enums;

public enum Permits {
    SEE_USER,
    DELETE_USER,
    UPDATE_USER,
    SEE_COMPANY,
    DELETE_COMPANY,
    UPDATE_COMPANY,
    SEE_JOBS,
    DELETE_JOB,
    SEE_PUBLICATION,
    DELETE_PUBLICATION,
    UPDATE_PUBLICATION,
    SEE_LIKES,
    DELETE_LIKE,
    GIVE_A_LIKE,
    SEE_COMMENTS,
    DELETE_COMMENTS,
    UPDATE_COMMENTS,
    SEE_FOLLOWERS,
    SEE_FOLLOWED,
    DELETE_FOLLOW,
    START_FOLLOW




}
