package TP_Final.devhire.Security.Enums;

public enum Permits {
    READ_PROFILE,
    UPDATE_PROFILE,
    DELETE_ACCOUNT,
    LOGIC_DOWN,
    LOGIC_UP,

    READ_DEVS,
    FILTER_DEVS,
    UPDATE_ACADEMIC_INFO,
    UPDATE_JOB_EXPERIENCE,
    UPDATE_SKILLS,

    READ_COMPANIES,
    FILTER_COMPANIES,

    CREATE_PUBLICATION,
    READ_PUBLICATIONS,
    UPDATE_PUBLICATION,
    DELETE_PUBLICATION,
    FILTER_PUBLICATIONS,

    FOLLOW,
    UNFOLLOW,
    FILTER_FOLLOWS,
    READ_FOLLOWS,
    READ_FOLLOWERS,
    READ_FOLLOWING,
    FILTER_FOLLOWERS,
    FILTER_FOLLOWING,
    DEACTIVATE_FOLLOW,
    REACTIVATE_FOLLOW,

    LIKE_PUBLICATION,
    UNLIKE_PUBLICATION,
    FILTER_LIKES,
    READ_LIKES,

    CREATE_COMMENT,
    READ_COMMENTS,
    FILTER_COMMENTS,
    UPDATE_COMMENT,
    DELETE_COMMENT,

    READ_JOBS,
    CREATE_JOB,
    UPDATE_JOB,
    DELETE_JOB,
    FILTER_JOBS,
    READ_JOB_REQUIREMENTS,
    READ_AVAILABLE_SKILLS,
    ADD_JOB_REQUIREMENT,

    APPLY_TO_JOB,
    DELETE_APPLY,
    READ_APPLICATIONS,
    READ_OWN_APPLICATIONS,
    FILTER_APPLICATIONS,
    READ_APPLICANTS,
    FILTER_APPLICANTS,
    DISCARD_APPLICANT

}
