package TP_Final.devhire.Model.Enums;

public enum HardSkills {
    JAVA, PYTHON, C, C_PLUS_PLUS,JAVASCRIPT,TYPESCRIPT,C_SHARP,GO,RUBY,SWIFT,
    KOTLIN,HTML5,CSS3,JAVASCRIPT_FRAMEWORKS,BACKEND_DEVELOPMENT,RESTFUL_APIS,
    GRAPHQL,SQL,MYSQL,POSTGRESQL,SQL_SERVER,NOSQL,MONGODB,REDIS,CASSANDRA,
    DATABASE_DESIGN,DATABASE_MODELING
}
