package TP_Final.devhire.Model.Enums;

public enum SoftSkills {
    PROBLEM_SOLVING, CRITICAL_THINKING, ATTENTION_TO_DETAIL, TEAMWORK, COMMUNICATION,
    ADAPTABILITY, TIME_MANAGEMENT, SELF_MOTIVATION, CREATIVITY, RESPONSIBILITY,
    COLLABORATION, EMPATHY, STRESS_MANAGEMENT, OPENNESS_TO_FEEDBACK, CONTINUOUS_LEARNING,
    WORK_ETHIC, DECISION_MAKING, CONFLICT_RESOLUTION, ORGANIZATIONAL_SKILLS, PATIENCE
}
